/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Frame1 extends java.awt.Frame implements Runnable {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        setSize(500,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        t2 = new java.awt.TextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        t1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(t1);
        t1.setBounds(30, 40, 400, 40);

        button1.setLabel("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(30, 130, 57, 24);

        t2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(t2);
        t2.setBounds(30, 180, 400, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    public void run()
    {
         while(true)
        {
            String s=t1.getText();
            String s1=s.substring(0,1);
            String s2=s.substring(1);
            t1.setText(s2+s1);
            try{
                Thread.sleep(500);
            }catch(Exception ee){}
        }
    }
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
       Thread t=new Thread(this);
       t.start();
       Thread1 t1=new Thread1();
       t1.start();
    }//GEN-LAST:event_button1ActionPerformed
    class Thread1 extends Thread
    {
        public void run()
        {
            while(true)
            {
                java.util.Date d=new java.util.Date();
                t2.setText(d+"");
                try{
                        Thread.sleep(1000);
                }catch(Exception ee){}
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         new Frame1().setVisible(true);       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    // End of variables declaration//GEN-END:variables
}
