/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
/**
 *
 * @author Administrator
 */
public class Frame1 extends java.awt.Frame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        setSize(400,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b2 = new java.awt.Button();
        b1 = new java.awt.Button();
        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        b3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 153));
        setTitle("ABCD");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        b2.setLabel("Cancel");
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2MouseEntered(evt);
            }
        });
        add(b2);
        b2.setBounds(80, 170, 130, 30);

        b1.setLabel("OK");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        add(b1);
        b1.setBounds(80, 120, 140, 30);

        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setText("label1");
        add(label1);
        label1.setBounds(158, 54, 120, 36);

        textField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        add(textField1);
        textField1.setBounds(90, 210, 160, 40);

        b3.setText("jButton1");
        add(b3);
        b3.setBounds(90, 270, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        textField1.setText("SDFGSSDFDS");
    }//GEN-LAST:event_b1ActionPerformed

    private void b2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseEntered
        // TODO add your handling code here:
        b2.setBackground(new Color(255,150,200));
    }//GEN-LAST:event_b2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b1;
    private java.awt.Button b2;
    private javax.swing.JButton b3;
    private java.awt.Label label1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
